 module.exports.productCategories = {
    electronics: {
        laptop: ["Performance",
            "Battery Life",
            "Portability",
            "Processor",
            "RAM",
            "Storage",
            "Display",
            "Graphics",
            "Operating System",
            "Connectivity",
            "Ports",
            "Design",
            "Keyboard",
            "Audio",
            "Warranty"],
        mobile:["Performance",
            "Battery Life",
            "Portability",
            "Processor",
            "RAM",
            "Storage",
            "Display",
            "Graphics",
            "Operating System",
            "Connectivity",
            "Ports",
            "Design",
            "Keyboard",
            "Audio",
            "Warranty"],

        TV:["Performance",
            "Battery Life",
            "Portability",
            "Processor",
            "RAM",
            "Storage",
            "Display",
            "Graphics",
            "Operating System",
            "Connectivity",
            "Ports",
            "Design",
            "Keyboard",
            "Audio",
            "Warranty"],
       
    },
    clothing: {
        shirt: [
            'Fashion',
            'Quality',
            'Comfort',
            'Versatility',
            'Elegance',
            'Functionality',
            'Sustainability',
            'Affordability',
            'Trend',
            'Fit'
          ],
        dress: [
            'Fashion',
            'Quality',
            'Comfort',
            'Versatility',
            'Elegance',
            'Functionality',
            'Sustainability',
            'Affordability',
            'Trend',
            'Fit'
          ],
       
        jeans: [
            'Fashion',
            'Quality',
            'Comfort',
            'Versatility',
            'Elegance',
            'Functionality',
            'Sustainability',
            'Affordability',
            'Trend',
            'Fit'
          ]
       
        },
    home: [
        "furniture",
        "kitchen appliances",
        "home decor",
        "bedding",
        "lighting",
    ],
    books: [
        "fiction",
        "non-fiction",
        "fantasy",
        "biography",
        "self-help",
    ],
    sports: [
        "fitness equipment",
        "sports apparel",
        "yoga mat",
        "basketball",
        "running shoes",
    ],
};